### ISSUE TITLE
Support watching for Ingress?

### ISSUE THREAD

**Issue by nabadger** [bitnami-labs/kubewatch#100]
Hi,

Can someone confirm if this is supported or not? I don't think it is (I don't see it in the kubewatch code). 

I also had a quick look into k8s.io/api/core/v1.

**Comment by nabadger** [comment]
Ok, turns out Ingress is in extensions (v1beta1)

**Comment by nabadger** [comment]
I think I have this working nearly - I'll submit a PR soon to support this.

**Comment by tylerauerbeck** [comment]
@nabadger Would love to see a PR for this. Once you're ready, go ahead and submit this and we can take a look at getting it merged.

**Comment by nabadger** [comment]
@tylerauerbeck  I've created a PR at #108 although it looks like there's a merge-conflict at the moment.

**Comment by tylerauerbeck** [comment]
Resolved by #108
