### ISSUE TITLE
Deleted secrets (and likely other resources) do not display correctly

### ISSUE THREAD

**Issue by nkashy1** [bitnami-labs/kubewatch#101]
I just set up kubewatch (in-cluster) to listen on pods, deployments, services, and secrets.

Tested things out with some dummy secrets. It looks as if secret deletion events (and probably any resource deletion events?) are not being handled correctly:

![loose-lips](https://user-images.githubusercontent.com/8016073/39463653-ef62e5dc-4ccd-11e8-9eac-8d5387b65ac9.png)

**Comment by tylerauerbeck** [comment]
@nkashy1 We're actually working through PR #99 right now to resolve this. This has been a known issue (as you can see through a number of other open issues), but we're pretty close to getting this resolved. Stay tuned. I'll shoot out an update once this gets merged.

**Comment by tylerauerbeck** [comment]
@nkashy1 This has been merged. Feel free to pull the master branch and give this a shot.

**Comment by nkashy1** [comment]
@tylerauerbeck : Nice, I will have a look tonight. Thank you!

**Comment by tylerauerbeck** [comment]
Resolved by #99. Please feel free to reopen if you continue to see issues.
