### ISSUE TITLE
should we create official bitnami images?

### ISSUE THREAD

**Issue by vtuson** [bitnami-labs/kubewatch#107]
Seems like the project is quite popular and we dont have latest and greatest images that are kept up-to-date.

I would suggest that we create a bitnami official image that does:
* single image that uses a two stage process to build and create the prod/binary image
* base it on mini-deb (at the moment is the easiest way for us to automate the creation of new images)

Would that work for you? @jjo @sebgoa @tylerauerbeck @carrodher

**Comment by jjo** [comment]
@vtuson +1, looks like a good candidate indeed for `bitnami/bitnami-docker-kubewatch`
(ie alongside other images we recently added there), also given that src code is pretty
straightforward and well written/documented.

**Comment by vtuson** [comment]
right, was my thoughts. Happy to add it into the backlog. We need to finish up automating some of the new containers but this should be in the list.

**Comment by carrodher** [comment]
LGTM, we can include it for future iterations

**Comment by sebgoa** [comment]
let's hear from @tylerauerbeck see if that would be a problem or not.

**Comment by tylerauerbeck** [comment]
Completely agree, would love to see this happen. Would just need some help from folks on the bitnami side to make this happen.

**Comment by tylerauerbeck** [comment]
@jjo @vtuson @carrodher Any update on this?

**Comment by peterfication** [comment]
Here is the respective Helm charts update PR: https://github.com/kubernetes/charts/pull/5871

**Comment by tylerauerbeck** [comment]
@carrodher Just so that we're all on the same page (and hopefully so we can get this documented on the README), can you explain how exactly this is all rigged up? Specifically, if we make changes in this repo, how do those changes get picked up by the bitnami-docker-kubewatch repo? Then ultimately is the goal to get this integrated with the kubewatch helm chart?

**Comment by tompizmor** [comment]
Hi @tylerauerbeck!

In Bitnami there is a service continuously checking for new releases of the software that we package. For the kubewatch project, it is tracking the [github release page](https://github.com/bitnami-labs/kubewatch/releases).

When we detect that there is a new release, we have a fully automated pipeline to download the new source code, compile the binary, build a docker image and test it. 

If the test passed successfully, we update the Dockerfile in the [bitnami-docker-kubewatch](https://github.com/bitnami/bitnami-docker-kubewatch) repo and create a release of the docker image. This is also automated.

At that point, circle ci automatically build the docker image and push it to Dockerhub and other registries. And finally, it would also send a PR to the kubernetes/chart repo updading the application and chart version and updating the docker image.

Some of the above is already documented in the [bitnami-docker-kubewatch readme](https://github.com/bitnami/bitnami-docker-kubewatch#why-use-bitnami-images)

**Comment by tylerauerbeck** [comment]
@tompizmor Thanks for the clarification. This makes a lot more sense now. I'll go ahead and close this issue now that I believe all of this to be rigged up appropriately.
