### ISSUE TITLE
Unknown user

### ISSUE THREAD

**Issue by peterfication** [bitnami-labs/kubewatch#117]
With the current version (`kubewatch: 0.0.4`, `helm chart: 0.4.0`) I get this error:

```
ERROR: logging before flag.Parse: E0613 14:33:29.073005       1 reflector.go:205] github.com/bitnami-labs/kubewatch/pkg/controller/controller.go:377: Failed to list *v1beta1.Deployment: deployments.apps is forbidden: User "system:serviceaccount:system:kubewatch" cannot list deployments.apps at the cluster scope: Unknown user "system:serviceaccount:system:kubewatch"
```
(I have `kubewatch` installed in the namespace `system`)

I checked with `kubectl` and I can see the user, the cluster role and the cluster role binding. Do you have any ideas, why it does not work?

I know there is issue https://github.com/bitnami-labs/kubewatch/issues/91 but I think it is not related as I used the helm chart to create the deployment.

**Comment by d47zm3** [comment]
please check out my PR, I've hit that issue too, and sent possible solution (RBAC)
https://github.com/kubernetes/charts/pull/6567

**Comment by peterfication** [comment]
Yes that fixed it for me. Closing this now in favour of https://github.com/kubernetes/charts/pull/6567

**Comment by peterfication** [comment]
Thanks a lot @d47zm3
