### ISSUE TITLE
Inconsistent behavior between tuna/kubewatch:v0.0.1 and github code

### ISSUE THREAD

**Issue by john-callahan** [bitnami-labs/kubewatch#125]
Seems that using the tuna/kubewatch:v0.0.1 works ok, but after cloning the repo and rebuilding the image (no changes made) the behavior is different.  Does git have all the latest code used to create the v0.0.1 image?

image using v0.0.1
![image](https://user-images.githubusercontent.com/38055148/43334569-add8c394-919b-11e8-89a0-f0e40c3306e9.png)

cloned/rebuilt image with no changes
![image](https://user-images.githubusercontent.com/38055148/43334677-d548f8b8-919b-11e8-8ab5-19f5eae8574f.png)

Also getting these errors in the logs for the rebuilt image.

ERROR: logging before flag.Parse: E0727 16:09:18.530583       1 reflector.go:205] github.com/bitnami-labs/kubewatch/pkg/controller/controller.go:398: Failed to list *v1beta1.Deployment: User "system:serviceaccount:logging:kubewatch" cannot list apps.deployments in project "logging"
 
using openshift v3.5.5.31.48 / kubernetes v1.5.2

**Comment by mkmik** [comment]
obsolete; please re-open if it still happens
