### ISSUE TITLE
Can we bring this project back to life?

### ISSUE THREAD

**Issue by tylerauerbeck** [bitnami-labs/kubewatch#202]
We recently got some attention pointed our way via: https://twitter.com/learnk8s/status/1200131082454220801

It also seems as though there is some interest in this project judging by the `Insights` info that we have. I'd be happy to give some of my time in order to start going through the backlog of Issues and PR here, but would like to see if others feel the same. If that's the case, I'd also like to look at least at adding some additional reviewers to help us maintain this repo (and even define a path towards becoming a maintainer, etc.).

Is this something that others are interested in?

cc/ @jjo @jbianquetti-nami (Feel free to add others that you think would be appropriate for this discussion)

**Comment by testlabauto** [comment]
@jjo @jbianquetti-nami  I recently started using the project and would like to see it come back to life.  I am currently using the webhook functionality and it is very useful for me as a way to initiate integration tests in our dev/staging k8s environments.

**Comment by bjorn-ali-goransson** [comment]
This project is nice, already has "good seo" (ie. looking for auditing tools this one comes up), and is very simplistic in its implementation. Doesn't try to do too much.

I'd like to help out with my best effort.

One thing I lack (maybe I didn't find it) is some kind of integration tests, perhaps one could use Kubernetes In Docker (kind) ... ?

**Comment by mkmik** [comment]
project resurrected
