### ISSUE TITLE
is bitnami/kubewatch the correct image?

### ISSUE THREAD

**Issue by naridnevahgar** [bitnami-labs/kubewatch#225]
Hi, i pulled the yaml files from the master and applied them on my local. 
The pod comes up as expected, but it doesn't appear to be latest.

`
ERROR: logging before flag.Parse: E0701 07:33:34.951497       1 reflector.go:205] github.com/bitnami-labs/kubewatch/pkg/controller/controller.go:377: Failed to list *v1beta1.Deployment: the server could not find the requested resource
`

I see a commit on https://github.com/bitnami-labs/kubewatch/blob/master/pkg/controller/controller.go a couple of days back mentioning about version change for Deployment. So is there a new image available?

**Comment by mkmik** [comment]
yes the image is correct; the issue with k8s >=1.16 has been fixed recently (in #200) but no new release has been published yet. We'll publish very soon
