### ISSUE TITLE
Failed to list *v1.Deployment: the server could not find the requested resource

### ISSUE THREAD

**Issue by bparinas** [bitnami-labs/kubewatch#237]
Hello,

I tried to setup kubewatch v0.1.0 (latest) in Docker EE 2.0 (outdated) with the ff. specs.

Docker EE v2.0
Kubernetes version v1.06
Docker engine v17.06.2-ee-8, API version 1.30

I encountered this error:
_**E0803 - reflector.go:123 github.com/bitnami-labs/kubewatch/pkg/controller/controller.go:466 Failed to list *v1.Deployment: the server could not find the requested resource**_

Let me know if you can recommend an older release of kubewatch that will work in that specs.

**Comment by mkmik** [comment]
apps/v1.Deployment have been introduced in k8s 1.9

We aim at supporting the latest k8s versions and at least the previous last four previous versions which are released every quarter. Thus, one year old clusters are fully supported. If it's older than that it may or may not work.

1.9 has been released Dec 16, 2017 placing it outside our support window.
