### ISSUE TITLE
Query on webhook handler

### ISSUE THREAD

**Issue by ashishchalak** [bitnami-labs/kubewatch#238]
Is there any document or example to use a webhook handler.

https://github.com/bitnami-labs/kubewatch/tree/master/pkg/handlers/webhook

What is the url that I should be passing to see the notifications?

My requirement is to capture the k8s events via restcalls.

**Comment by mkmik** [comment]
why closed? have you found/received an answer?

**Comment by ashishchalak** [comment]
I was able to create a rest API and get the JSON response from kubewatch.

**Comment by ashishchalak** [comment]
Is there any public slack channel or some way for quick Q and A

**Comment by mkmik** [comment]
> Is there any public slack channel or some way for quick Q and A
not that I know of

**Comment by ashishchalak** [comment]
Can you please check on this issue: https://github.com/bitnami-labs/kubewatch/issues/239
