### ISSUE TITLE
Doesn't show the namespace

### ISSUE THREAD

**Issue by akefirad** [bitnami-labs/kubewatch#275]
As can be seen below, the message doesn't contain the namespace for some events:
<img width="382" alt="Screen Shot 2021-07-27 at 12 38 37" src="https://user-images.githubusercontent.com/2142363/127141099-d93f329a-0a5b-4f85-ba93-d760e90ba399.png">
Our configuration is pretty much the default one. Let me know if you need more information. Thanks.

**Comment by rjhenry** [comment]
Looks to be the same issue as #267 - you might want to also subscribe to that!
