### ISSUE TITLE
Configurable resource types to be watched

### ISSUE THREAD

**Issue by ngtuna** [bitnami-labs/kubewatch#43]

**Comment by ngtuna** [comment]
I consider keep this issue open although #45 getting merged already. Somehow we should think more on supported options for resources to be watched. At this moment, it's running like this:

```console
// rc, po and svc would be watched
$ kubewatch config resource --rc --po --svc

// only svc would be watched
$ kubewatch config resource --svc
```
By default, supported changes are: create, delete, update. We can always think about configurations more specific like I only want to watch added services, or deleted pod, or updated rc.

**Comment by tylerauerbeck** [comment]
@ngtuna Not sure where this stands. If you could point me in the right direction I'd be more than happy to work on this.

**Comment by tylerauerbeck** [comment]
Part two of this issue (granular event alerting) is now being worked as part of #105

**Comment by arunkumarmurugesan** [comment]
I'm also looking for similar kind of granular event alerting. Also, want to understand why its keep sending update notification into slack channel even there is no action performed in the cluster. 

FYI:
kubewatch
A service in namespace kube-system has been updated:
