### ISSUE TITLE
make a Helm chart

### ISSUE THREAD

**Issue by sebgoa** [bitnami-labs/kubewatch#5]
with the [helm](https://github.com/kubernetes/helm) client installed simply do:

```
$ helm create kubewatch
```

Then stick the RC/Deployment yaml file in the Chart `/templates` directory, edit the `Chart.yaml` file

Test that you can deploy kubewatch with `helm`.

that's it.

**Comment by jstriebel** [comment]
see kubernetes/charts#2705

**Comment by sebgoa** [comment]
oh cool. thanks so much.

**Comment by tylerauerbeck** [comment]
@sebgoa So it looks like the kubewatch chart has graduated to a stable chart (which is good!). The downside is that this is based on the 0.3 release, which is fairly far behind master at this point. It also appears that it's hosted out of ngtuna's docker repo. Is there somewhere better to put this (a bitnami-labs repo perhaps)?

**Comment by vtuson** [comment]
@tylerauerbeck if we create an official image #107 , then we can hook up the helm CI/CD into it that should create updates/PR for charts and make sure we keep it up to date

**Comment by tylerauerbeck** [comment]
@vtuson Similar to my comment over in #107, now that there is an official image .. is it already tied into the helm CI/CD? Or is that something that still needs to happen?

**Comment by tylerauerbeck** [comment]
Helm chart has been created and the new release process is rigged up to submit a PR whenever a new version of kubewatch is released.
