### ISSUE TITLE
Extend support watching deployment, daemonset, replicaset

### ISSUE THREAD

**Issue by ngtuna** [bitnami-labs/kubewatch#50]

**Comment by sebgoa** [comment]
Let's do third party resources as well. maybe just after deployments....

because those are quite handy.

**Comment by tylerauerbeck** [comment]
#74 adds functionality for deployments. Have an initial build ready for DS and RS after resolving #75 .

**Comment by tylerauerbeck** [comment]
Deployments, daemonsets and replicasets are now included in Kubewatch. My assumption is to skip TPR and go straight to CRD (which I'll create a seperate issue for)
