### ISSUE TITLE
hipchat

### ISSUE THREAD

**Issue by ajohnstone** [bitnami-labs/kubewatch#56]
Would be awesome to support hipchat

**Comment by rajatjindal** [comment]
This has been merged, can someone else try it out and let us know of any issues

**Comment by caquinovs** [comment]
@rajatjindal are v1 hipchat tokens supported? separately, i've been looking at https://developer.atlassian.com/hipchat/guide/hipchat-rest-api/api-access-tokens to try to generate a v2 token, it looks like we can create either addon tokens or user generated tokens - which ones can kubewatch support?

**Comment by caquinovs** [comment]
@ajohnstone have you had a chance to try this out with hipchat integration yet? if so, i would love to hear any feedback you may have

**Comment by ajohnstone** [comment]
@caquinovs Unfortunately since I wrote this ticket the company I work at has moved to slack :|

**Comment by rajatjindal** [comment]
@caquinovs I generated the token using HipChat webinterface > Integrations > Build your own integrations.

I am not quite sure if its v1 or v2. (the version we use is v2)
