### ISSUE TITLE
bump client-go version

### ISSUE THREAD

**Issue by tylerauerbeck** [bitnami-labs/kubewatch#75]
Kubewatch appears to currently be running utilizing version = "v3.0.0-beta.0" . We probably want to bump this to a later (latest?) release to take advantage of new functionality and resource types (CRD, etc.)

**Comment by sebgoa** [comment]
yes, need to update to v5

**Comment by tylerauerbeck** [comment]
Hoping maybe some more experienced hands can help out here. I've got all of the api components moved to where they need to be (i.e. change from k8s.io/client-go/api to k8s.io/api). However when I go to run dep ensure -update, I get the following:
```

ensure Solve(): No versions of gopkg.in/inf.v0 met constraints:
	v0.9.0: unable to update checked out version: : command failed: [git checkout 3887ee99ecf07df5b447e9b00d9c0b2adaa9f3e4]: exit status 128
```

This appears to be a dependency from k8s.io/apimachinery. Still fairly new to go (and especially dependency management). Any pointers. Once I'm able to resolve this, I should be good to go to commit the changes to bump client-go and switch the pointers to bitnami-labs.

I've also got the changes to add some of the newere features (CRD, DaemonSet) but didn't know what the preference was in regards to PR size (single PR -- multiple new features versus multiple PR with more defined feature sets).

**Comment by tylerauerbeck** [comment]
@sebgoa Alright. Got past this issue. Looks like it was an issue with my local dep cache. But client-go 5.0 (and 5.0.1) are still causing some heartache. Looks like there is an issue here:

```
# github.com/bitnami-labs/kubewatch/vendor/k8s.io/client-go/tools/clientcmd/api
vendor/k8s.io/client-go/tools/clientcmd/api/zz_generated.deepcopy.go:38:15: scheme.AddGeneratedDeepCopyFuncs undefined (type *runtime.Scheme has no field or method AddGeneratedDeepCopyFuncs)
vendor/k8s.io/client-go/tools/clientcmd/api/zz_generated.deepcopy.go:39:3: undefined: conversion.GeneratedDeepCopyFunc
vendor/k8s.io/client-go/tools/clientcmd/api/zz_generated.deepcopy.go:43:3: undefined: conversion.GeneratedDeepCopyFunc
vendor/k8s.io/client-go/tools/clientcmd/api/zz_generated.deepcopy.go:47:3: undefined: conversion.GeneratedDeepCopyFunc
vendor/k8s.io/client-go/tools/clientcmd/api/zz_generated.deepcopy.go:51:3: undefined: conversion.GeneratedDeepCopyFunc
vendor/k8s.io/client-go/tools/clientcmd/api/zz_generated.deepcopy.go:55:3: undefined: conversion.GeneratedDeepCopyFunc
vendor/k8s.io/client-go/tools/clientcmd/api/zz_generated.deepcopy.go:59:3: undefined: conversion.GeneratedDeepCopyFunc
make: *** [Makefile:16: build] Error 2
```
Is there a specific reason for targetting version 5 instead of the more recent release (6)? The changes I've made to bump client-go still work with the newer version and the more recent release also seems to take care of the error above.

Let me know what you think. PR is ready to go with client-go 6.0 and is submitted (mostly to get a PR out there to fix an issue with compiling because of a missed import #77 ).

**Comment by ngtuna** [comment]
@tylerauerbeck Thanks for submitting the patch. For your above issue, I guess it's because of the mismatch in the apimachinery's revision. With client-go v5, it should be `019ae5ada31de202164b118aee88ee2d14075c31`. If you want you can try it again. There is no specific reason to stick client-go to v5 and IMO v6 is fine. I will look at your PR shortly.

**Comment by tylerauerbeck** [comment]
@sebgoa Good to close once #78 is merged
