### ISSUE TITLE
Replace imports from skippbox with bitnamilabs

### ISSUE THREAD

**Issue by tylerauerbeck** [bitnami-labs/kubewatch#76]
Right now, all the imports inside of kubewatch still refer to the skippbox repo. I'm assuming this isn't breaking anything because there are some redirects happening at this point. But to reduce any confusion (and any future breaks should the redirect dissapear), it's probably smart to update these to point directly to bitnamilabs.

**Comment by sebgoa** [comment]
yes good point

**Comment by tylerauerbeck** [comment]
@sebgoa I've actually taken care of this in a branch based off of #74 . When / if that PR is merged, I can go ahead and submit a followup that will take care of this and #75 (or we can break them apart if you think that's better).

**Comment by tylerauerbeck** [comment]
@sebgoa Good to close once #78 is merged.
