### ISSUE TITLE
Building failed

### ISSUE THREAD

**Issue by udrwt** [bitnami-labs/kubewatch#77]
Building failed with error:
controller/controller.go:131:4: undefined: batch_v1

It seems batch_v1 from import is missed.

**Comment by tylerauerbeck** [comment]
@udrwt That's my fault. Submitting a PR to resolve the issue now. To fix this in the meantime, you can add the following to the imports in pkg/controller/controller.go
`batch_v1 "k8s.io/client-go/pkg/apis/batch/v1"`

**Comment by udrwt** [comment]
@tylerauerbeck : Thanks for sharing fix.. :)
after these change build was success.

I have on more doubt. I am trying kubewatch first time and want to use it locally, i.e. trying to run on local machine and want to capture notifications on local machine itself rather then on publishing on slack.

Could you please help.

Thanks in advance for help.. :) :)

**Comment by tylerauerbeck** [comment]
@udrwt I can't say that this is the best way, but here's how I've been testing on my local machine due to being lazy and not setting up a test slack channel.

- startup minikube (or however you plan on running your test cluster)
- pull down and build kubewatch (which sounds like you've gotten to this point)
- `make build` will create your kubewatch binary within that same directory
- You can then run ./kubewatch config resource --svc --ns to watch your cluster for new services or namespaces.
- `./kubewatch config resource --help` will give you an entire listing of resources that are available. The only one that isn't configured right now is replicaset, but that will be coming soon.
- You would then just kick off kubewatch with `./kubewatch` after configuring your desired resources and it should output everything to your console

Let me know if that makes sense. If not, feel free to reach back out and I can try to throw something a little more substantial together to get you up and running.

**Comment by udrwt** [comment]
@tylerauerbeck :
Hi,
Really appreciate your quick response... :+1: 
 I tried as you suggested ... :)

After executing ./kubewatch, I have deployed/delete one application using  kubectl create/delete command but each time I can see below logs:

"time="2018-01-12T13:51:12Z" level=info msg="Processing change to pod: default/webserver-54848c775f-528v2" pkg=kubewatch-pod"

it seems kubewatch is sending notification that object is changed, but not sending detailed info, like either created or deleted.

Please confirm if my understanding is correct or correct me.
Also is there any option to enable/disable detailed logs?

**Comment by tylerauerbeck** [comment]
@udrwt Sorry for the delay. That's a good point. I do see that the logging only tells you that _something_ has happened, not exactly what has happened. I can look at building that out here shortly after I clean up a few other things (unless anybody else wants to take a run at it).

cc/ @ngtuna @sebgoa in case there are any flags I'm missing that already take care of this

**Comment by udrwt** [comment]
I was trying kubewatch because i want to monitor my objects. But seems it is not working as expected. After running locally i thought  "I am running it locally and it is showing limited logs, in slack channel I'll be able to see detail logs.

As per the README doc, after applying below command, output should be available at slack channel.
_>kubectl create -f kubewatch.yaml_
 
but in my case kubewatch pod was created but no output was updated in slack channel.
In slack channel, notifications are updated after running “kubewatch” command on console.   

Also in slack channel for one pod deletion, I am receiving below notifications and deletion information is missing ... :(

kubewatch
A pod in namespace default has been created: webserver2-56ff445c89-z8m4r
[3:59 PM]
kubewatch
A pod in namespace default has been created: webserver2-56ff445c89-st9n7
[3:59 PM]
kubewatch
A pod in namespace default has been created: webserver2-56ff445c89-st9n7
[3:59 PM]
kubewatch
A pod in namespace default has been created: webserver2-56ff445c89-z8m4r
[4:00 PM]
kubewatch
A pod in namespace default has been created: webserver2-56ff445c89-z8m4r
[4:00 PM]
kubewatch
A  in namespace  has been :

I tried hard to debug it but as i am new for golang, I just concluded that at blow statement (in controller/controller.go) object was deleted, so no meta object will be available which leads to empty field and null notification.

if !exists {
		c.eventHandler.ObjectDeleted(obj)
return nil

I think deletion notification should send before object deletion.

**Comment by tylerauerbeck** [comment]
@udrwt So I see a few issues here. First as you mentioned, if you're just looking at the command line logging output (setting slack aside for the moment) -- the logging had previously just mentioned that something had changed. I took what you had mentioned and added some more descriptive logging so that now we know whether a resource was deleted, updated or created.

Another issue, was that if you tried to watch deployment resources, you would get an error both at the command line logging and through slack, which is why you see lines like this:
`[4:00 PM] kubewatch A in namespace has been :`

This was caused because I had deployment returning the wrong resource type. I've corrected this and this will be pushed in a PR soon.

The last issue appears to have something to do with the slack handler;specifically. It looks like regardless of the action type, it thinks that the action is created (versus the other two options of updated and deleted). I'll start taking a look at that next. I'll keep you updated as I have some time to look at this. More to come soon.

**Comment by ngtuna** [comment]
@udrwt I am not sure if you has configured kubewatch properly to help it send msgs to your slack. You can run `./kubewatch config slack --help` and point out the proper token & channel information. You can anytime verify and update your configuration at `~/.kubewatch.yaml` file. This file is created silently to store configuration parameters.

@tylerauerbeck I tried to build latest changes on master branch and run kubewatch locally but got this issue:

```
Tunas-MacBook-Pro:kubewatch tuna$ ./kubewatch 
INFO[0000] Starting kubewatch controller                 pkg=kubewatch-service
ERROR: logging before flag.Parse: E0128 14:50:06.466938   18634 runtime.go:66] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
/Users/tuna/workspace/gocode/kubewatch/src/github.com/bitnami-labs/kubewatch/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:72
/Users/tuna/workspace/gocode/kubewatch/src/github.com/bitnami-labs/kubewatch/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:65
/Users/tuna/workspace/gocode/kubewatch/src/github.com/bitnami-labs/kubewatch/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:51
/usr/local/Cellar/go/1.9.2/libexec/src/runtime/asm_amd64.s:509
/usr/local/Cellar/go/1.9.2/libexec/src/runtime/panic.go:491
/usr/local/Cellar/go/1.9.2/libexec/src/runtime/panic.go:63
/usr/local/Cellar/go/1.9.2/libexec/src/runtime/signal_unix.go:367
/Users/tuna/workspace/gocode/kubewatch/src/github.com/bitnami-labs/kubewatch/vendor/k8s.io/client-go/kubernetes/clientset.go:170
/Users/tuna/workspace/gocode/kubewatch/src/github.com/bitnami-labs/kubewatch/pkg/controller/controller.go:413
/Users/tuna/workspace/gocode/kubewatch/src/github.com/bitnami-labs/kubewatch/vendor/k8s.io/client-go/tools/pager/pager.go:39
/Users/tuna/workspace/gocode/kubewatch/src/github.com/bitnami-labs/kubewatch/vendor/k8s.io/client-go/tools/pager/pager.go:77
/Users/tuna/workspace/gocode/kubewatch/src/github.com/bitnami-labs/kubewatch/vendor/k8s.io/client-go/tools/cache/listwatch.go:97
/Users/tuna/workspace/gocode/kubewatch/src/github.com/bitnami-labs/kubewatch/vendor/k8s.io/client-go/tools/cache/reflector.go:249
/Users/tuna/workspace/gocode/kubewatch/src/github.com/bitnami-labs/kubewatch/vendor/k8s.io/client-go/tools/cache/reflector.go:204
/Users/tuna/workspace/gocode/kubewatch/src/github.com/bitnami-labs/kubewatch/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133
/Users/tuna/workspace/gocode/kubewatch/src/github.com/bitnami-labs/kubewatch/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:134
/Users/tuna/workspace/gocode/kubewatch/src/github.com/bitnami-labs/kubewatch/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88
/Users/tuna/workspace/gocode/kubewatch/src/github.com/bitnami-labs/kubewatch/vendor/k8s.io/client-go/tools/cache/reflector.go:203
/Users/tuna/workspace/gocode/kubewatch/src/github.com/bitnami-labs/kubewatch/vendor/k8s.io/client-go/tools/cache/controller.go:122
/Users/tuna/workspace/gocode/kubewatch/src/github.com/bitnami-labs/kubewatch/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:54
/Users/tuna/workspace/gocode/kubewatch/src/github.com/bitnami-labs/kubewatch/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:71
/usr/local/Cellar/go/1.9.2/libexec/src/runtime/asm_amd64.s:2337
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x1b31195]

goroutine 38 [running]:
github.com/bitnami-labs/kubewatch/vendor/k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/Users/tuna/workspace/gocode/kubewatch/src/github.com/bitnami-labs/kubewatch/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:58 +0x111
panic(0x1c7e120, 0x258e490)
	/usr/local/Cellar/go/1.9.2/libexec/src/runtime/panic.go:491 +0x283
github.com/bitnami-labs/kubewatch/vendor/k8s.io/client-go/kubernetes.(*Clientset).AppsV1beta1(0x0, 0x0, 0x0)
	/Users/tuna/workspace/gocode/kubewatch/src/github.com/bitnami-labs/kubewatch/vendor/k8s.io/client-go/kubernetes/clientset.go:170 +0x5
github.com/bitnami-labs/kubewatch/pkg/controller.newControllerDeployment.func1(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x1db4427, ...)
	/Users/tuna/workspace/gocode/kubewatch/src/github.com/bitnami-labs/kubewatch/pkg/controller/controller.go:413 +0x41
...
```

It sitll has more log lines but I cut at the most intersting line `/Users/tuna/workspace/gocode/kubewatch/src/github.com/bitnami-labs/kubewatch/pkg/controller/controller.go:413 +0x41`

Be aware I am configuring kubwatch to send notifies only for k8s deployment. Any clue ?

**Comment by tylerauerbeck** [comment]
@ngtuna @udrwt The remainder of the issue being tracked here is now being worked as part of #80. Would it be better to close this as the original issue has been resolved and track the remaining issue in the new issue to keep things clean?

**Comment by tylerauerbeck** [comment]
@udrwt Going to go ahead and close this since the remaining issues are being tracked and are better documented in #80 . Please feel free to reopen if you have any issue.
