### ISSUE TITLE
Kubewatch for Jobs monitoring

### ISSUE THREAD

**Issue by PavelKarpenka** [bitnami-labs/kubewatch#83]
Hello!

Does Kubewatch support jobs at the moment? It seems like jobs are not included in 0.0.3 release. But I see jobs in the current state of Master. I manually added "jobs" resource to configamp and clusterrole and of course it did not start working. So my questions are:
1. Is it possible to make Kubewatch working with jobs at the current state of the project?
If not,
2. Are you going to add jobs support in your next release? And what is the approximate date of the next release?
Thanks a lot!
 Pavel

**Comment by tylerauerbeck** [comment]
@PavelKarpenka Jobs are actually included in the current `master` branch , so you could go ahead and pull the master branch and just build from source if you wanted to test this right away. I know @ngtuna had mentioned cutting a new release shortly, but I don't know there there's currently a solid date as to when this should be expected. I can check on this and I'll update you when I know more.

**Comment by ngtuna** [comment]
@tylerauerbeck I will spend half an hour today to cut the release. Sorry for the delay.

**Comment by PavelKarpenka** [comment]
@tylerauerbeck Thank you! 
I tried to build from the current master state.

What I do:
1. Clone the repo
2. 
```
make builder-image
```
3. 
```
make binary-image
```
Getting kubewatch docker image on this step 
4. Tag and push this image to my registry
 
Then I try to run a pod in my GCP cluster using the following:
1. my image built from master
2. Configmap created with [kubewatch-configmap.yaml](https://github.com/bitnami-labs/kubewatch/blob/master/kubewatch-configmap.yaml) with added resource
      jobs: true
3. Pod config [kubewatch-in-cluster.yaml](https://github.com/bitnami-labs/kubewatch/blob/master/kubewatch-in-cluster.yaml) with my image in the right place
4. Clusterrole, clusterrolebinding and serviceaccount as we use RBAC

Pod creation fails with the message: 
```
level=fatal msg="Can not get kubernetes config: stat /root/.kube/config: no such file or directory"
```

I tried to correct in configmap  `.kubewatch.yaml` to `config` and in pod spec `mountPath: /root` to `mountPath: /root/.kube`
In this case pod starts but I don't see any messages in slack

When I start pod with image `tuna/kubewatch:v0.0.1` - it works for everything except Jobs 

Did somebody test current state of the master? Does it work?
Thanks a lot in advance!

**Comment by moshe0076** [comment]
@PavelKarpenka - Had the same problem.   Just created the config file in /root/.kube as config and in /root
 as  .kubewatch.yaml and it works.

**Comment by PavelKarpenka** [comment]
@moshe0076 sorry for maybe dumb question. 
How did you exactly do this?
Added in Dockerfile.run something like the following?
```
RUN touch /root/.kube/config && \
    touch /root/.kubewatch.yaml
```
Thank you!

**Comment by moshe0076** [comment]
@PavelKarpenka I did it with a configmap in Kubernetes

**Comment by PavelKarpenka** [comment]
@moshe0076 Thanks a lot! It works.

**Comment by tylerauerbeck** [comment]
@PavelKarpenka I see that you have this working now. Are you able to configure Kubewatch to watch jobs? If so, are we okay to close this issue?

**Comment by PavelKarpenka** [comment]
@tylerauerbeck yes, this issue can be closed, thank you! 
I just have one question regarding jobs monitoring. Is it possible to detect such events as "Terminated: Completed" and "Terminated: Error" for pods generated by jobs? It could be very useful. Because when we want to monitor jobs, we in most cases want to know the status of a terminated job pod.
Thank you!

**Comment by tylerauerbeck** [comment]
@PavelKarpenka That's actually something that we've been discussing (more granular event alerting and extended alerting based on some types of objects). I'm going to open up another issue to track that task as I believe it's going to be a much larger discussion. I'll loop you into that issue as well so you can follow along.

**Comment by rkumarcisco** [comment]
Hello ,
I have set up kubewatch and configured it with Slack messaging service.Now want to configure in such a way that the alerts are sent to Email directly from KUbernetes cluster using Kubewatch.Is it possible to do that?

**Comment by vitobotta** [comment]
Hi! Is it possible somehow to receive notifications with the status of a job (succeeded/failed)? It seems the notifications only says when the job was created/updated? Thanks :)
