### ISSUE TITLE
ObjectUpdated not used?

### ISSUE THREAD

**Issue by gytisgreitai** [bitnami-labs/kubewatch#85]
Sorry for a dummy question, but looking at `controller.go` I only see `ObjectDeleted` and `ObjectCreated` invoked, but it seems that `ObjectUpdate`  only exists on handlers, or am I missing something obvious?

**Comment by gytisgreitai** [comment]
ok, nevermind it seems that the master is probably in some sort of WIP status, cause it looks there are too many broken things

**Comment by rossedman** [comment]
@gytisgreitai Was wondering the same thing. Trying to understand how to determine update vs creation in the controller.
